#!/usr/bin/env python3
"""Generate a simple ns-3 topology file from repository YAML configs."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from packet_core_modes import mode_definition, resolve_mode  # noqa: E402


def load_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"missing config file: {path}")
    data = yaml.safe_load(path.read_text()) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"config file must contain a YAML mapping: {path}")
    return data


def scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "1" if value else "0"
    return str(value)


def tier_bps(service_data: dict[str, Any], tier_name: str, fallback: int) -> int:
    for tier in service_data.get("service_tiers", []):
        if tier.get("name") == tier_name:
            return int(tier.get("target_bps", fallback))
    return fallback


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scenario", type=Path, default=ROOT / "network/config/scenario_5uav.yaml")
    parser.add_argument("--endpoints", type=Path, default=ROOT / "network/config/endpoints.yaml")
    parser.add_argument("--service-tiers", type=Path, default=ROOT / "network/config/service_tiers.yaml")
    parser.add_argument("--radio", type=Path, default=ROOT / "network/config/radio_24ghz.yaml")
    parser.add_argument(
        "--radio-backend-config",
        type=Path,
        default=ROOT / "network/config/radio_backend.yaml",
    )
    parser.add_argument("--jammers", type=Path, default=ROOT / "network/config/jammers.yaml")
    parser.add_argument("--run-id", default="manual")
    parser.add_argument("--run-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--duration", type=float, default=None)
    parser.add_argument("--node-state-file", type=Path, default=None)
    parser.add_argument("--packet-core-mode", default=None)
    parser.add_argument("--allow-mock-sionna", action="store_true")
    args = parser.parse_args()

    scenario = load_yaml(args.scenario)
    endpoints = load_yaml(args.endpoints)
    service = load_yaml(args.service_tiers)
    radio_cfg = load_yaml(args.radio)
    load_yaml(args.radio_backend_config)
    jammer_cfg = load_yaml(args.jammers)

    scenario_radio = scenario.get("radio", {})
    radio = radio_cfg.get("radio", {})
    ns3 = radio_cfg.get("ns3", {})
    offered = radio_cfg.get("traffic_offered_bps", {})
    tos = radio_cfg.get("priority_tos", {})
    traffic_policy = service.get("traffic_class_policy", {})

    sionna = endpoints.get("ipc", {}).get("sionna_provider", {})
    command_post = scenario.get("command_post", {})
    robots = scenario.get("robots", [])
    if len(robots) != 5:
        raise SystemExit(f"expected 5 UAV robots in {args.scenario}, found {len(robots)}")

    traffic_classes = list(scenario.get("traffic_classes") or traffic_policy.keys())
    if set(traffic_classes) != {"control", "payload", "additional_data"}:
        raise SystemExit(f"unexpected traffic classes: {traffic_classes}")

    try:
        packet_core_mode = resolve_mode(radio_cfg, args.packet_core_mode)
        packet_core = mode_definition(packet_core_mode)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc

    if not packet_core["runtime_selectable"]:
        raise SystemExit(
            "packet-core mode "
            f"{packet_core_mode!r} is {packet_core['status']}; "
            "runtime is intentionally fail-closed until the implementation and no-bypass proof exist. "
            "Run network/ns3/packet_core_modes.py --purpose evaluation for dependency reporting."
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.run_dir.mkdir(parents=True, exist_ok=True)

    duration_s = args.duration
    if duration_s is None:
        duration_s = float(ns3.get("simulation_duration_s", 20))

    lines = [
        "# Generated by network/ns3/generate_ns3_topology.py",
        f"run_id {args.run_id}",
        f"run_dir {args.run_dir}",
        f"duration_s {duration_s}",
        f"channel_rate_bps {int(ns3.get('channel_rate_bps', 1000000))}",
        f"channel_delay_ms {float(ns3.get('channel_delay_ms', 2))}",
        f"queue_max_packets {int(ns3.get('queue_max_packets', 100))}",
        f"packet_core_mode {packet_core_mode}",
        f"packet_core_status {packet_core['status']}",
        f"packet_core_runtime_selectable {1 if packet_core['runtime_selectable'] else 0}",
        f"packet_core_shared_medium_model {packet_core['shared_medium_model']}",
        f"packet_core_fidelity_note {packet_core['fidelity_note_id']}",
        f"sionna_host {sionna.get('host', '127.0.0.1')}",
        f"sionna_port {int(sionna.get('port', 5090))}",
        f"sionna_deadline_ms {int(ns3.get('sionna_deadline_ms', 50))}",
        f"sionna_query_period_s {float(ns3.get('sionna_query_period_s', 1.0))}",
        f"node_state_file {args.node_state_file}" if args.node_state_file else "node_state_file",
        f"allow_mock_sionna {1 if args.allow_mock_sionna else 0}",
        f"carrier_hz {int(radio.get('carrier_hz', scenario_radio.get('carrier_hz', 2400000000)))}",
        f"bandwidth_hz {int(radio.get('bandwidth_hz', scenario_radio.get('bandwidth_hz', 1000000)))}",
        f"tx_power_dbm {float(radio.get('tx_power_dbm', scenario_radio.get('tx_power_dbm_default', 33.0)))}",
        f"noise_figure_db {float(radio.get('receiver_noise_figure_db', 6.0))}",
        "",
        "# node <id> <role> <x_m> <y_m> <z_m> <antenna>",
    ]

    cp_pos = command_post.get("position_m", [0.0, 0.0, 20.0])
    lines.append(
        "node {id} {role} {x} {y} {z} {antenna}".format(
            id=command_post.get("id", "cp"),
            role=command_post.get("role", "command_post"),
            x=float(cp_pos[0]),
            y=float(cp_pos[1]),
            z=float(cp_pos[2]),
            antenna=command_post.get("antenna", "omni"),
        )
    )

    for robot in robots:
        pos = robot.get("nominal_radio_position_m")
        if pos is None:
            launch_pos = robot.get("position", [0.0, 0.0, 0.0])
            pos = [launch_pos[0], launch_pos[1], max(float(launch_pos[2]), 80.0)]
        lines.append(
            "node {name} uav {x} {y} {z} {antenna}".format(
                name=robot["name"],
                x=float(pos[0]),
                y=float(pos[1]),
                z=float(pos[2]),
                antenna=robot.get("antenna", "omni"),
            )
        )

    lines += ["", "# traffic_class <name> <priority> <target_bps> <deadline_ms> <offered_bps> <tos>"]
    for name in traffic_classes:
        policy = traffic_policy.get(name, {})
        target = tier_bps(service, policy.get("minimum_tier", ""), 1000)
        lines.append(
            "traffic_class {name} {priority} {target} {deadline} {offered} {tos}".format(
                name=name,
                priority=int(policy.get("queue_priority", 2)),
                target=target,
                deadline=int(policy.get("deadline_ms", 1000)),
                offered=int(offered.get(name, target)),
                tos=int(tos.get(name, 0)),
            )
        )

    lines += ["", "# link <tx> <rx> <traffic_class>"]
    cp_id = command_post.get("id", "cp")
    for robot in robots:
        uav = robot["name"]
        for traffic_class in traffic_classes:
            lines.append(f"link {cp_id} {uav} {traffic_class}")
            lines.append(f"link {uav} {cp_id} {traffic_class}")

    lines += ["", "# emitter <id> <enabled> <x_m> <y_m> <z_m> <center_hz> <bandwidth_hz> <power_dbm> <duty_cycle>"]
    for jammer in jammer_cfg.get("jammers", []):
        pos = jammer.get("position_m", [0.0, 0.0, 0.0])
        lines.append(
            "emitter {id} {enabled} {x} {y} {z} {center} {bandwidth} {power} {duty}".format(
                id=jammer["id"],
                enabled=scalar(jammer.get("enabled", False)),
                x=float(pos[0]),
                y=float(pos[1]),
                z=float(pos[2]),
                center=int(jammer.get("center_hz", radio.get("carrier_hz", 2400000000))),
                bandwidth=int(jammer.get("bandwidth_hz", radio.get("bandwidth_hz", 1000000))),
                power=float(jammer.get("power_dbm", 40.0)),
                duty=float(jammer.get("duty_cycle", 1.0)),
            )
        )

    args.output.write_text("\n".join(lines) + "\n")
    print(f"Wrote ns-3 topology: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
